/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import viewmodel.TKThuocTinhSP_View;
import service.ITKThuocTinh_Service;
import service.impl.TKThuocTinh_Sevice;

/**
 *
 * @author 
 */
public class TKThuocTinhSP extends javax.swing.JPanel {
    ITKThuocTinh_Service ttSP_sv = new TKThuocTinh_Sevice();
    List<TKThuocTinhSP_View> list;
    DefaultTableModel mol;
    /**
     * Creates new form TKThuocTinhSP
     */
    public TKThuocTinhSP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblTKThuocTinhSP = new javax.swing.JTable();

        tblTKThuocTinhSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "stt", "Mã", "Tên Sản Phẩm", "Size", "Đã Bán", "Còn Lại"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblTKThuocTinhSP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTKThuocTinhSP;
    // End of variables declaration//GEN-END:variables
    public void filltbl(String ma){
        list = ttSP_sv.tkByMa(ma);
        mol = (DefaultTableModel) tblTKThuocTinhSP.getModel();
        mol.setRowCount(0);
        for (TKThuocTinhSP_View t : list) {
            mol.addRow(new Object[]{t.getStt(),t.getMaSP(),t.getTenSP(),t.getSize(),t.getSlBan(),t.getSlCon()});
        }
    }
}
